# Target(prefix='Wertschöpfungs', word='Kette', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='angegriffen', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='angepöbelt', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='tuscheln', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='kichern', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(prefix='Bloß', word='Stellung', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='aufbereitet', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='entwenden', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='versehen', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='durchforsten', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Abhilfe', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='theologisch', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='Akronym', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# # Target(prefix='Entfernungs', word='Radius', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(prefix='Bau', word='Gewerbe', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='Akzentuierung', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(prefix='Ausgleichs', word='Zahlung', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='Bronchitis', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(prefix='gesamt', word='fiskalisch', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='delegieren', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Pappe', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(prefix='Schalt', word='Kreis', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='verschlüsselt', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(prefix='Fälschungs', word='sicher', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='Rheuma', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='synthetisieren', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Gefäß', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Röntgenstrahlung', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='patentieren', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Acetylsalicylsäure', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Enzym', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Aminosäure', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Saatgut', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Weizen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Gerste', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='altruistisch', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(prefix='fach', word='kundig', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='Gebrechen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='angesetzt', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Anatomie', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Gewerbe', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='antioxidantisch', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='lancieren', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Muffel', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='heraufbeschworen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Anleger', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='verprellen', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='eingebrochen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Steuersatz', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Organ', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Judikative', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(prefix='Personen', word='Verkehr', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='Absatz', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='falten', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Wahlurne', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='verabschieden', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='gefangene', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Kapitulation', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='entgegengenommen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='ausgelaufen', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='abgedankt', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='menschenverachtend', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='pferchen', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Befugnis', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='aufgestellt', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='Senat', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='erheben', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='Faser', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='titulieren', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
# Target(word='perfid', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(word='Lockmittel', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='verschleiß', fix='', lb=False, rb=False, cs=False, mode=NOUN_MODE),
# Target(word='unsachgemäß', fix='', lb=False, rb=False, cs=False, mode=ADJECTIVE_MODE),
# Target(prefix='Versand', word='Handel', fix='', lb=False, rb=False, cs=False, mode=COMPOUND_NOUN_MODE),
# Target(word='behaupten', fix='', lb=False, rb=False, cs=True, mode=VERB_MODE),
